# Generated by Django 4.2.2 on 2023-07-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='static/posts/'),
        ),
    ]
